# This workflow will generate and update the lists in the 'lists' branch each night at 0 UTC

name: generate-lists

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:

jobs:
  generate-lists:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Fetch SushiSwap Tokenlist 
      uses: wei/wget@v1
      with:
        args: -O sushiswap.json https://raw.githubusercontent.com/sushiswapclassic/token-list/master/sushiswap.tokenlist.json
    - name: Tokenlist Data
      run: |
        mkdir data
    - name: Commit files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -B lists
        rm sushiswap.tokenlist.json
        git add *.json -f
        git commit -m "chore(sync): sushiswap: $(date)" -a || true
        git tag `date "+lists-%Y%m%d%H%M%S"`
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: tokenlists
        force: true
        tags: true
