# This workflow will generate and update the lists in the 'lists' branch each night at 0 UTC

name: generate-lists

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:

jobs:
  generate-lists:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Fetch SushiSwap Tokenlist 
      uses: wei/wget@v1
      with:
        args: -O sushiswap.json https://raw.githubusercontent.com/sushiswapclassic/token-list/master/sushiswap.tokenlist.json
    - name: Generate TXT and JSON files for all assets
      run: |
        mkdir data
    - name: Commit files
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git checkout lists
        rm sushiswap.tokenlist.json
        mv data/* .
        date --rfc-3339=seconds | sed 's/ /T/' >> VERSION
        git add *.json -f
        git add VERSION
        git commit -m "chore(sync): sushiswap: $(date)" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: lists
